### ISSUE TITLE
Docs: Host the python notebooks investigating the different datatypes used in FLINT simulation

### ISSUE THREAD

**Issue by padmajabhol** [moja-global/moja_global_docs#161]
The python notebooks that I recently worked upon can be found here(https://github.com/padmajabhol/LFX-mentorship-progress-tracker/tree/main/FLINT-Datatype). Each of them contains a small description of the data type and instructions on how to open them. They are mainly of five types - JSON, GeoTIFF, Shapefile, CSV, SQL DB. 

As suggested by @aornugent, we can use an extension to render them on our sphinx site.

Before I proceed with the task, I had a few things to clarify:
1. Additional documentation to go along with the files
2. Particular section/ page where they could be rendered

cc: @aornugent @HarshCasper @chicken-biryani

**Comment by chicken-biryani** [comment]
I have a few questions as well-

1) For the rough work do you think it's okay to make use of GitBook.

"GitBook is free forever for individual use. GitBook gives individuals 10 public and private spaces, custom domains and Git Sync at no cost"

So to edit things out... The navigation etc can be put over here before making it public? And we could go bunch wise instead of one by one?

2) Shall we switch to sphinx 4.1.1... or other?

**Comment by HarshCasper** [comment]
@chicken-biryani @padmajabhol 

I don't see why GitBook is being recommended when we have the entire documentation website setup using Docusaurus. If the requirements are for rough work, why not use HackMD or Google Docs for the purpose? 

@padmajabhol — Look over this for your use-case: https://nbsphinx.readthedocs.io/en/0.8.8/ 
@chicken-biryani — What is the rationale behind switching to Sphinx 4.11 or "other"?

**Comment by Namyalg** [comment]
@aornugent @HarshCasper @chicken-biryani ,
I am working on developing the documentation for the various datatypes, and how they are used in the context of the project. Is there anything else that should be covered? And how will the documentation be presented, will it have separate .md files for each datatype or will it be a part of the jupyter notebooks?
