### ISSUE TITLE
Updated Branding for ReadtheDocs

### ISSUE THREAD

**Issue by ksocksTR33Z** [moja-global/moja_global_docs#50]
moja global has a new brand and visiual style we should apply to ReadtheDocs.

Some support from the team to help update the stylesheet would be great (some directions here: https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html).

Attached are logos, brand assets, and a color palette to use in updating the stylesheet. The font is DM Sans
![Logos_1000x1000pxLogo-w-icon-1](https://user-images.githubusercontent.com/81089179/113035817-8ee29000-9161-11eb-88c8-bb71c48b54b4.png)
![Logos_1000x1000pxLogo-w-icon-2](https://user-images.githubusercontent.com/81089179/113035818-8f7b2680-9161-11eb-9569-86412cf093df.png)

[Mojaglobal_BrandGuidelines_2021.pdf](https://github.com/moja-global/moja_global_docs/files/6232235/Mojaglobal_BrandGuidelines_2021.pdf)

**Comment by aornugent** [comment]
@Tlazypanda @waridrox

**Comment by waridrox** [comment]
Great @ksocksTR33Z 🎉, since RTD theme is _primarily light coloured_, would it be better to go with the light colored moja-global brand identity or the dark one that would better go with the color palette as well...? Tbh, both look great but if there's a preference of one over the other then pls voice your opinioins. Thanks!

<img width="676" alt="Screenshot 2021-03-31 at 12 19 41 PM" src="https://user-images.githubusercontent.com/58583793/113102228-6028f000-921b-11eb-8f92-0ef320b5099d.png">

**Comment by ksocksTR33Z** [comment]
@waridrox I would suggest that the Earth Green be the base/primary background color with the lighter greens and blues as accent colors for other elements (text, borders/frames, etc.) That's how the majority of the new website will be developed as well.

**Comment by waridrox** [comment]
I've been very busy lately, sorry about that 😅. How does this stack up against the expectations @ksocksTR33Z ? Is it too distracting for the user ? Pls give an unbiased opinion on the same so that we can further improve upon. Thanks!

<img width="1258" alt="Screenshot 2021-04-05 at 3 48 56 AM" src="https://user-images.githubusercontent.com/58583793/113522897-db92f480-95c1-11eb-8626-b52874b934a9.png">

<img width="1262" alt="Screenshot 2021-04-05 at 3 49 14 AM" src="https://user-images.githubusercontent.com/58583793/113522902-e5b4f300-95c1-11eb-9cee-3f709fde152a.png">

**Comment by ksocksTR33Z** [comment]
@waridrox this looks great!

**Comment by waridrox** [comment]
👍 @ksocksTR33Z, I wanted to draw your attention to the text housing links. Is `marine blue` color for text and links in `midnight green` color fine or do we need to make some tweaking ?

<img width="684" alt="Screenshot 2021-04-05 at 10 16 11 PM" src="https://user-images.githubusercontent.com/58583793/113599664-8952e180-965c-11eb-818d-da38de2a1cdc.png">

**Comment by ksocksTR33Z** [comment]
@waridrox the main text on the site is MIDNIGHT GREEN. Hyperlinked text is MOSS GREEN. Hope that helps
